# Generated by Django 5.2 on 2025-04-18 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_value', models.CharField(max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
