# Generated by Django 5.2 on 2025-04-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_appointmentuser_user_type_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
